image: wangqipeng/wecloud_train:v0.2.0

setup: |
  uname -a
  echo "hello world"
  python3 --version
  pip3 install -r requirements.txt

run: |
  python
  main.py
  --gpu

profile: |
  python 
  main.py 
  --gpu 
  --profiling